-- create right Sales Orders table
DROP TABLE "CBASTO"."v.tb.salesOrders";
CREATE COLUMN TABLE "CBASTO"."v.tb.salesOrders" 
	("ORDER_ID" NVARCHAR(10),
	 "CALENDAR_ID" NVARCHAR(2),
	 "CUSTOMER_ID" NVARCHAR(18),
	 "ITEM_ID" NVARCHAR(4),
	 "ITEMS_SOLD" TINYINT CS_INT,
	 "SALES_AMOUNT" DOUBLE);


-- create right Customer table
DROP TABLE "CBASTO"."v.tb.customer";
CREATE COLUMN TABLE "CBASTO"."v.tb.customer" ("CUSTOMER_ID" NVARCHAR(18),
	 "CUSTOMER_CHILDREN" SMALLINT CS_INT,
	 "CUSTOMER_GENDER_ID" NVARCHAR(6),
	 "CUSTOMER_MARITAL_STATUS_ID" SMALLINT CS_INT,
	 "CUSTOMER_MORTGAGE_ID" SMALLINT CS_INT,
	 "CUSTOMER_AGE_ID" TINYINT CS_INT,
	 "CUSTOMER_INCOME_ID" SMALLINT CS_INT,
	 "CUSTOMER_NAME" NVARCHAR(23),
	 "CUSTOMER_JOB" NVARCHAR(18),
	 "CUSTOMER_EDUCATION" NVARCHAR(8),
	 "CUSTOMER_EMAIL" NVARCHAR(29),
	 "CUSTOMER_CITY" NVARCHAR(9),
	 "CUSTOMER_TIMESTAMP" NVARCHAR(16)) UNLOAD PRIORITY 5 AUTO MERGE 
;

-- create right Calendar table
DROP TABLE "CBASTO"."v.tb.calendar";
CREATE COLUMN TABLE "CBASTO"."v.tb.calendar" ("CALENDAR_ID" NVARCHAR(18),
	 "CALENDAR_YEAR" NVARCHAR(4),
	 "CALENDAR_MONTH" NVARCHAR(6),
	 "CALENDAR_YYYYMM" NVARCHAR(7)) UNLOAD PRIORITY 5 AUTO MERGE 
;

-- create right Customer Gender table
DROP TABLE "CBASTO"."v.tb.customerGender";
CREATE COLUMN TABLE "CBASTO"."v.tb.customerGender" ("CUSTOMER_GENDER_ID" NVARCHAR(18),
	 "CUSTOMER_GENDER_NAME" NVARCHAR(6)) UNLOAD PRIORITY 5 AUTO MERGE 
;