SELECT
	 "ORDER_ID",
	 "ITEM_ID",
	 "MONTH",
	 "CUSTOMER_NAME",
	 "CUSTOMER_GENDER_IN",
	 "CALENDAR_MONTH_DATE",
	 "MONTH_ATTRIBUTE",
	 sum("ITEMS_SOLD") AS "ITEMS_SOLD",
	 sum("SALES_AMOUNT") AS "SALES_AMOUNT" 
FROM "_SYS_BIC"."HF17.Modeling.NormalizedScenario/cvViewSalesOrderDate"('PLACEHOLDER' = ('$$ip_month$$',
	 '02')) 
WHERE (("CALENDAR_MONTH_DATE" BETWEEN ('201010') 
		and ('201209'))) 

GROUP BY "ORDER_ID",
	 "ITEM_ID",
	 "MONTH",
	 "CUSTOMER_NAME",
	 "CUSTOMER_GENDER_IN",
	 "CALENDAR_MONTH_DATE",
	 "MONTH_ATTRIBUTE"
	ORDER BY "ORDER_ID" ASC;

SELECT
	 "ORDER_ID",
	 "ITEM_ID",
	 "MONTH",
	 "CUSTOMER_NAME",
	 "CUSTOMER_GENDER_IN",
	 "CALENDAR_MONTH_DATE",
	 "MONTH_ATTRIBUTE",
	 sum("ITEMS_SOLD") AS "ITEMS_SOLD",
	 sum("SALES_AMOUNT") AS "SALES_AMOUNT" 
FROM "_SYS_BIC"."HF17.Modeling.AnalyticScenario/cvViewSalesOrderDate"('PLACEHOLDER' = ('$$ip_month$$',
	 '02')) 
WHERE (("CALENDAR_MONTH_DATE" BETWEEN ('201010') 
		and ('201209'))) 
GROUP BY "ORDER_ID",
	 "ITEM_ID",
	 "MONTH",
	 "CUSTOMER_NAME",
	 "CUSTOMER_GENDER_IN",
	 "CALENDAR_MONTH_DATE",
	 "MONTH_ATTRIBUTE"
		ORDER BY "ORDER_ID" ASC	 